# Generated by Django 6.1 on 2026-08-13 05:19

import django.db.models.deletion
import study.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['participant_code'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stimulus_id', models.CharField(blank=True, max_length=120)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('timeout', 'Timed out'), ('manual', 'Ended by participant'), ('abandoned', 'Abandoned (no explicit end received)')], default='in_progress', max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='study.participant')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_source', models.CharField(choices=[('webcam', 'Webcam'), ('screen', 'Screen')], max_length=10)),
                ('sequence', models.PositiveIntegerField()),
                ('is_last', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to=study.models.recording_chunk_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_chunks', to='study.studysession')),
            ],
            options={
                'ordering': ['session', 'stream_source', 'sequence'],
                'unique_together': {('session', 'stream_source', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_source', models.CharField(choices=[('webcam', 'Webcam'), ('screen', 'Screen')], max_length=10)),
                ('file', models.FileField(blank=True, upload_to=study.models.recording_path)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='study.studysession')),
            ],
            options={
                'unique_together': {('session', 'stream_source')},
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.CharField(max_length=120)),
                ('section_id', models.CharField(max_length=120)),
                ('question_id', models.CharField(max_length=120)),
                ('answer_value', models.CharField(max_length=500)),
                ('effort_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('presented_at', models.DateTimeField(blank=True, help_text='When the question screen appeared (client clock).', null=True)),
                ('answered_at', models.DateTimeField(blank=True, help_text='When the participant submitted the answer (client clock).', null=True)),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='study.studysession')),
            ],
            options={
                'ordering': ['session', 'server_received_at'],
                'unique_together': {('session', 'question_id')},
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('session_started', 'Session started (login)'), ('session_ended', 'Session ended'), ('screen_shown', 'Screen shown'), ('server_hit', 'Server endpoint hit'), ('webcam_recording_started', 'Webcam recording started'), ('webcam_recording_stopped', 'Webcam recording stopped'), ('screen_recording_started', 'Screen recording started'), ('screen_recording_stopped', 'Screen recording stopped'), ('fullscreen_entered', 'Fullscreen entered'), ('fullscreen_exited', 'Fullscreen exited'), ('other', 'Other')], max_length=40)),
                ('screen_name', models.CharField(blank=True, max_length=60)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('client_timestamp', models.DateTimeField(blank=True, help_text='Timestamp reported by the browser, if any.', null=True)),
                ('server_timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_path', models.CharField(blank=True, max_length=255)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='study.studysession')),
            ],
            options={
                'ordering': ['session', 'server_timestamp'],
                'indexes': [models.Index(fields=['session', 'event_type'], name='study_activ_session_d15ea2_idx')],
            },
        ),
    ]
