# Generated by Django 6.1 on 2026-08-26 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activityevent',
            options={'ordering': ['session_key', 'epoch_ms']},
        ),
        migrations.RemoveIndex(
            model_name='activityevent',
            name='study_activ_session_d15ea2_idx',
        ),
        migrations.AddField(
            model_name='activityevent',
            name='epoch_ms',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='meta',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='study.participant'),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='activityevent',
            name='stream_source',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='client_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('login_complete', 'Login Complete'), ('module_start', 'Module Start'), ('module_end', 'Module End'), ('recording_start', 'Recording Start'), ('recording_stop', 'Recording Stop'), ('question_shown', 'Question Shown'), ('question_answered', 'Question Answered'), ('session_end', 'Session End'), ('session_started', 'Session Started'), ('screen_shown', 'Screen Shown'), ('server_hit', 'Server Hit'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='request_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='screen_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='study.studysession'),
        ),
    ]
