# Generated by Django 6.1 on 2026-09-22 10:59

import study.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_studysession_consent_given_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='sidecar_file',
            field=models.FileField(blank=True, null=True, upload_to=study.models.recording_path),
        ),
    ]