# Generated by Django 6.1 on 2026-09-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_recording_sidecar_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='answered_epoch_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='presented_epoch_ms',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('login_complete', 'Login Complete'), ('module_start', 'Module Start'), ('module_end', 'Module End'), ('recording_start', 'Recording Start'), ('recording_stop', 'Recording Stop'), ('question_shown', 'Question Shown'), ('question_answered', 'Question Answered'), ('session_end', 'Session End'), ('session_started', 'Session Started'), ('screen_shown', 'Screen Shown'), ('server_hit', 'Server Hit'), ('consent_given', 'Consent Given'), ('other', 'Other')], max_length=32),
        ),
        migrations.AlterField(
            model_name='questionresponse',
            name='answer_value',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='studysession',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]