# Generated by Django 6.1 on 2026-09-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_questionresponse_answered_epoch_ms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('login_complete', 'Login Complete'), ('module_start', 'Module Start'), ('module_end', 'Module End'), ('recording_start', 'Recording Start'), ('recording_stop', 'Recording Stop'), ('question_shown', 'Question Shown'), ('question_answered', 'Question Answered'), ('session_end', 'Session End'), ('session_started', 'Session Started'), ('screen_shown', 'Screen Shown'), ('server_hit', 'Server Hit'), ('consent_given', 'Consent Given'), ('fullscreen_entered', 'Fullscreen Entered'), ('fullscreen_exited', 'Fullscreen Exited'), ('webcam_recording_stopped', 'Webcam Recording Stopped'), ('screen_recording_stopped', 'Screen Recording Stopped'), ('click', 'Click'), ('text_input', 'Text Input'), ('matrix_page_next', 'Matrix Page Next'), ('matrix_page_shown', 'Matrix Page Shown'), ('rating_selected', 'PaaS Rating Selected'), ('end_study_opened', 'End-Study Modal Opened'), ('end_study_cancelled', 'End-Study Cancelled'), ('end_study_confirmed', 'End-Study Confirmed'), ('back_attempt', 'Back Button Attempt'), ('tab_hidden', 'Tab Hidden'), ('tab_visible', 'Tab Visible'), ('window_blur', 'Window Blur'), ('window_focus', 'Window Focus'), ('clipboard', 'Copy/Paste/Cut'), ('context_menu', 'Right Click'), ('page_hide', 'Page Hide'), ('other', 'Other')], max_length=32),
        ),
    ]
